EventPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('NeverMissIt.urls')), # redirecting to the app's url configuration.
]

NeverMissIt/urls.py
from django.urls import path
from . import views

app_name = 'NeverMissIt'

# all the url and the corresponding views.
urlpatterns = [
    #path('home/', views.homepage, name='homepage'),
    path('', views.homepage, name='homepage'),
    path('signup/', views.signuppage, name='signuppage'),
    path('login/', views.loginpage, name='loginpage'),
    path('logout/', views.logoutpage, name='logoutpage'),
    path('profile/', views.profilepage, name='profilepage'),
    path('create/', views.createeventpage, name='createeventpage'),
    path('detail/', views.detaileventpage, name='detaileventpage'),
    path('edit/', views.editeventpage, name='editeventpage'),
    path('register/', views.registereventpage, name='registereventpage'),
]

NeverMissIt/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# model for the created events taking the User "id" as the foreign key.
class EventDetails(models.Model):
    title = models.CharField(max_length=100, unique=True, verbose_name='Event Title')
    createduserid = models.ForeignKey(User, on_delete=models.CASCADE) #the foreign key to the User
    description = models.TextField(verbose_name='Event Description')
    eventdate = models.DateField(verbose_name='Event Date')
    location = models.CharField(max_length=200, verbose_name='Event Happening At')
    lastdatetoreg = models.DateField(verbose_name='Registration Deadline')
    maxparticipants = models.PositiveIntegerField(verbose_name='Max. members in a Team')

    def __str__(self):
        return self.title  # to show the tile of the event when accessing it as object

# model for the participant list of events using foreign key "id" from EventDetails for the event recognition and "id" from User for the team leader recognition
class EventParticipants(models.Model):
    eventid = models.ForeignKey(EventDetails, on_delete=models.CASCADE) # foreign key to the EventDetails for event recognition
    teamleader = models.ForeignKey(User, on_delete=models.CASCADE) # foreign key to the User to set the team leader as the registering user as default
    participants = models.TextField() # storing the participants names and is stored as a single string seperated by &.

    def __str__(self):
        return self.eventid.title + " (" + self.teamleader.username + ")" # shows the title and the team leader of the registered team, which is by default the User who is registering.

NeverMissIt/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, fields
from django import forms
from . import models

# the form used in the signup page. It is inheriting from the built in Model provided by django.
class SignUpForm(UserCreationForm):
    class Meta:
        model = User # using the model django provides. django.contrib.auth.models.User
        fields = ['username', 'email', 'password1', 'password2'] # choosing the fields to include in the form.

# this is to provide datepicking widget to some input fields in EventCreationForm.
class DatePicker(forms.DateInput):
    input_type = 'date'

# form for the event publishing process.
class EventCreationForm(forms.ModelForm):
    class Meta:
        model = models.EventDetails # creating the model EventDetails defined in models.py
        fields = ['title', 'description', 'eventdate', 'location', 'lastdatetoreg', 'maxparticipants'] # choosing fields to be included in the form
        widgets = {
            'eventdate':DatePicker(), # providing a datepicking widget to two of the fields in the form.
            'lastdatetoreg':DatePicker(),
        }

NeverMissIt/views.py
from django.contrib import auth
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from datetime import date

from .models import EventDetails, EventParticipants
from .forms import SignUpForm, EventCreationForm

# Create your views here.

# this is the public view page. this is accessible only when user is not logged in. It will get the Events' which has it's 'last date to register'
# today or later and pass it to the corresponding html template. If any of the event is selected, the user will be directed to the login page.
def homepage(request):
    if request.user.is_authenticated:
        return redirect('NeverMissIt:profilepage')

    else:
        # EventDetails.objects.filter(lastdatetoreg__gt=date.today()).order_by('lastdatetoreg')
        coming_events_in_order = EventDetails.objects.filter(lastdatetoreg__gte=date.today()).order_by('lastdatetoreg')
        context = {'events':coming_events_in_order}
        return render(request, 'NeverMissIt/homepage.html', context)

# this is the page for the sign up process. This is accessible only when user is not logged in. It is creating a form object from the SignUpForm in forms.py
# and passed to the corresponding html template. If the user submits the filled in data and is valid, the user account is created and is directed to the login
# page.
def signuppage(request):
    if request.user.is_authenticated:
        return redirect('NeverMissIt:profilepage')
    
    else:
        form = SignUpForm()

        if request.method == "POST":
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Account created succesfully for ' + form.cleaned_data.get('username'))
                return redirect('NeverMissIt:loginpage')

        context = {'form':form}
        return render(request, 'NeverMissIt/signuppage.html', context)

# this is the page for loggin in. This is accessible only when user is not logged in. It does not handle any form object. It receives the data from a form 
# set up in the html template and logs in the user if the usename and password matches and directs to the user profile page.
def loginpage(request):
    if request.user.is_authenticated:
        return redirect('NeverMissIt:profilepage')

    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('NeverMissIt:profilepage')
            else :
                messages.info(request, 'username and password does not match')

        context = {}
        return render(request, 'NeverMissIt/loginpage.html', context)


# this is view for logging out process. Only accessible when a user is logged in. redirects to the loginpage after logging out.
@login_required(login_url='NeverMissIt:loginpage') # only allowed if " LOGGED IN "
def logoutpage(request):
    logout(request)
    return redirect('NeverMissIt:loginpage')

# This is the view for the profile dashboard. The dashboard will show all the events the user has registered for (that is yet to happen and that got over also)
# , the events that are available to register for and the events that the user has created(both got over ones and the upcoming ones). 
# there is a link to the event creation page also. On selecting any of the event, user will be redirected to the correspondin pages.
@login_required(login_url='NeverMissIt:loginpage') # only allowed if " LOGGED IN "
def profilepage(request):
    registered_not_over = EventDetails.objects.filter( id__in=[x.eventid_id for x in EventParticipants.objects.filter(teamleader_id = request.user.pk) ] ).filter(eventdate__gte=date.today()).order_by('eventdate')
    registered_over = EventDetails.objects.filter( id__in=[x.eventid_id for x in EventParticipants.objects.filter(teamleader_id = request.user.pk) ] ).filter(eventdate__lt=date.today()).order_by('-eventdate')
    created_not_over = EventDetails.objects.filter(createduserid_id = request.user.pk).filter(eventdate__gte=date.today()).order_by('eventdate')
    created_over = EventDetails.objects.filter(createduserid_id = request.user.pk).filter(eventdate__lt=date.today()).order_by('-eventdate')
    available_events = EventDetails.objects.filter(lastdatetoreg__gte=date.today()).exclude( id__in=[x.eventid_id for x in EventParticipants.objects.filter(teamleader_id = request.user.pk) ] ).exclude( createduserid_id = request.user.pk ).order_by('lastdatetoreg')
    context = {'registered_not_over':registered_not_over, 'registered_over':registered_over, 'created_not_over':created_not_over, 'created_over':created_over, 'available_events':available_events}
    return render(request, 'NeverMissIt/profilepage.html', context)

# this is the event publishing page. It passes a form element to the template. User can input the details and submit and the event will be published.
# The events created can be deleted by the user if it has not got over yet.
@login_required(login_url='NeverMissIt:loginpage') # only allowed if " LOGGED IN "
def createeventpage(request):
    form = EventCreationForm()

    if request.method == "POST":
        form = EventCreationForm(request.POST)
        if form.is_valid():
            eventform = form.save(commit=False)
            eventform.createduserid_id = request.user.pk
            eventform.save()
            return redirect('NeverMissIt:profilepage')

    context = {'form':form}
    return render(request, 'NeverMissIt/createeventpage.html', context)

# This is the page showing the details of an event. If it is an event the user has registered for, the event details and the team members list will be shown
# if it is an event the user has created and that got over, the event details will be displayed.
@login_required(login_url='NeverMissIt:loginpage') # only allowed if " LOGGED IN "
def detaileventpage(request):
    eventid = request.GET['eventid']
    event = EventDetails.objects.get(pk=eventid)
    teammates = []
    #condition for the user for being the creator (EventDetails.objects.get(pk=eventid).createduserid_id==request.user.pk)
    #condition for the user if he is a registered participant ( it is the else condition for the previous one )
    if not EventDetails.objects.get(pk=eventid).createduserid_id == request.user.pk:
        team = EventParticipants.objects.get(teamleader_id=request.user.pk, eventid_id=eventid).participants
        teammates = team.split('&')
    context = {'event':event, 'teammates':teammates}
    return render(request, 'NeverMissIt/detaileventpage.html', context)

# This page is for deleting the event created by the user, if it has not got over yet.
@login_required(login_url='NeverMissIt:loginpage') # only allowed if " LOGGED IN "
def editeventpage(request):
    eventid = request.GET['eventid']
    event = EventDetails.objects.get(pk=eventid)

    if request.method == "POST":
        if bool(request.POST.get('delyesorno')):
            EventDetails.objects.filter(pk=eventid).delete()
            EventParticipants.objects.filter(eventid_id=eventid).delete()
            return redirect('NeverMissIt:profilepage')

    context = {'event':event}
    return render(request, 'NeverMissIt/editeventpage.html', context)

# This is the page for facilitating the user for registering for any event. the team members name can be entered and submitted.
@login_required(login_url='NeverMissIt:loginpage') # only allowed if " LOGGED IN "
def registereventpage(request):
    eventid = request.GET['eventid']
    no_of_teammates = EventDetails.objects.get(pk=eventid).maxparticipants - 1
    teammates = ["teammate "+str(x) for x in range(1, no_of_teammates+1)]
    event = EventDetails.objects.get(pk=eventid)

    if request.method == 'POST':
        t = []
        for i in teammates:
            t.append(request.POST.get(i).strip())
        while '' in t:
            t.remove('')
        team = "&".join(t)
        print(team)
        eventregister = EventParticipants(teamleader_id=request.user.pk, eventid_id=eventid, participants=team)
        eventregister.save()
        return redirect('NeverMissIt:profilepage')
    
    # passing teammates, eventdetail object of the current event
    context = {'teammates':teammates, 'event':event}
    return render(request, 'NeverMissIt/registereventpage.html', context)

NeverMissIt/templates/NeverMissIt/loginpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            color: black;
          margin: 0;
          padding: 0;
          background-image: url("https://images.unsplash.com/photo-1505909182942-e2f09aee3e89?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80");
          -webkit-background-size: cover;
          background-size: cover;
          font-family: sans-serif;
        }
        .login_box {
          width: 320px;
          background: rgba(255, 255, 255, 0.863);
          color: #000;
          top: 50%;
          left: 50%;
          position: absolute;
          transform: translate(-50%, -50%);
          box-sizing: border-box;
          padding: 60px 30px;
        }
        .avatar {
          width: 80px;
          height: 80px;
          border-radius: 50%;
          position: absolute;
          top: -40px;
          right: calc(50% - 40px);
        }
        h1 {
          margin-bottom: 10px;
          padding: 0 0;
          text-align: center;
          font-size: 22px;
        }
        .login_box p {
          margin: 0;
          padding: 0;
          font-weight: bold;
        }
        .login_box input {
          width: 100%;
          margin-bottom: 20px;
        }
        .login_box input[type="text"],
        input[type="password"],
        input[type="email"] {
          border: none;
          border-bottom: 1px solid #000;
          background: transparent;
          outline: none;
          height: 40px;
          color: #000;
          font-size: 16px;
        }
        .login_box input[type="submit"] {
          border: none;
          outline: none;
          height: 40px;
          background: #d22938;
          color: #fff;
          font-size: 18px;
          font-weight: bold;
          border-radius: 20px;
        }
        .login_box input[type="submit"]:hover {
          cursor: pointer;
          background: #ffc107;
          color: #000;
        }
        .right{
            position: absolute;
            right: 34px;
            top: 20px;
            display: inline-block;
            border-color: black;
        }
        .btn{
            margin: 0px 9px;
            background-color: rgb(255, 232, 21);
            color: yellow;
            padding: 4px 14px;
            border: 2px solid black;
            border-radius: 10px;
            cursor: pointer;
        }
        .btn:hover{
            background-color: grey;
        }
        #text2 a{
            text-decoration: none;
            font-family:cursive;
            font-weight: bolder;
            font-size: unset;
            float: right;
            background-color:transparent;
            color: rgb(0, 0, 0);
        }
        </style>
    
    <title>Login</title>
</head>
<body>
    <div class="login_box">
        <img src="https://blog.trello.com/hubfs/Productivity__236_-_More_Productive_and_Efficient_Events_402x.png" alt="login_avatar" class="avatar">
        <h1>Login</h1>
    <form action="" method="POST">

        {% csrf_token %}

        <p>Username</p>
        <input type="text" name='username'>
        <br><br>
        <p>Password</p>
        <input type="password" name='password'>
        <br><br>
        <input type="submit" value='login'>
    </form>

    {% for message in messages %}
        <br>
        {{message}}
        <br>
    {% endfor %}

    <br>
    <b>A new customer?</b>
    <a href="{% url 'NeverMissIt:signuppage' %}"><b>Signup</b></a>
    </div>
     <!-- right box for buttons -->
     <div class="right">
      <button class="btn" id="text2"><a href="{% url 'NeverMissIt:homepage' %}" id="log">Home</a></button>
  </div>
</body>
</html>

NeverMissIt/templates/NeverMissIt/profilepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Profile</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@700&display=swap" rel="stylesheet">
   
    <style>
        /* .row{
            display: grid;


        } */
        body{


        background-image: url("https://images.unsplash.com/photo-1505909182942-e2f09aee3e89?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80");
            background-repeat: no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;


        }
        .column{
            display: grid;
        float: left;
        background-color: black;

        }
        .lefttop {
            position: absolute;
            left: 32px;
            top: 18px;
            display: inline-block;
        }

        .lefttop img {
            width: 80px;
            height: 50px;
            border-radius: 80px;
        }


        .left{
        

            height: 90vh;
            width:30rem;
            border: 3px solid transparent;
            margin: 3px;
            color: white;


        }
        .middle{
        

        height: 70vh;
        width:30rem;
        border: 3px solid transparent;
        margin: 3px;
        color: white

    }
    .right{
        
/* change height to 100vh after modification */
        height:90vh;
        width:30rem;
        border: 3px solid transparent;
        margin: 3px;
        color: white

    }
    #grid1{
       
        margin: 3px;
        margin-top: 50px;
        font-family: 'Josefin Sans', sans-serif;
        font-size:22px;
        text-decoration: solid;
        text-align: center;
        color: rgb(255, 255, 25);
        font-weight: bolder;
        
    }
    #grid2{
        margin: 3px;
        margin-top: 6px;
        color: rgb(255, 255, 25);
        font-family: 'Dosis', sans-serif;
        text-align: center;
        list-style-type: none;
    }
    #grid3{
        list-style-type: none;
    }
    a{
        text-align:left;
        padding: 3px;
        font-family: 'Josefin Sans', sans-serif;
        color:black;
        font-weight: bolder;
        text-decoration: none;
        list-style-type: none;
        display:flex;
        
    }
    #link{
        display: flex;
        color:black;
        justify-content: center;
        font-family: 'Josefin Sans', sans-serif;
        text-decoration:none;
        border-radius: 3px;
        font-weight: bolder;
        font-size: 1rem;
        height: 2rem;
        padding-top: 6px;

        


    }
    #event{

        display: flex;
        background-color: whitesmoke;
        font-family: monospace;
        text-decoration: none;
        border: 2px dotted cyan;
        height: 2rem;
        padding-top: 1rem;
        width: 300px;
        font-weight: bolder;
        color:rgb(255, 255, 25);
        background-color: black;
        justify-content: center;
        font-size: 1rem;
        border-radius: 3px;
        margin-left: 3rem;
    }
    hr{
        border: 4px solid whitesmoke;
    }
    .btn {
            /* margin: 0px 9px; */
            background-color:rgb(255, 255, 25);
            padding: 4px 14px;
            width: 200px;
            height: 34px;
            border: 2px solid black;
            border-radius: 10px;
            cursor: pointer;
            float: right;
            margin-top: 8px;
            margin-left: 8.5rem;
            
        }

        .btn:hover {
            background-color:lightcyan;
        }
        .btn2 {
            /* margin-top: 0px;
            background-color:cyan;
            padding: 4px 14px;
            width: 200px;
            height: 34px;
            border: 2px solid black;
            border-radius: 10px;
            cursor: pointer;
            float: right; */

            margin-top: 0px;
            background-color:rgb(255, 232, 21);
            padding: 4px 14px;
            border: 2px solid black;
            border-radius: 10px;
            cursor: pointer;
            float: right;
        }

        .btn2:hover {
            background-color:lightcyan;
        }
        #head{
            text-align: center;
            font-family: 'Josefin Sans', sans-serif;
            font-weight:bolder;
            font-size: 40px;
            color: black;
            font-style:normal;
        }
        #text3{
            font-family: 'Dosis', sans-serif;
            font-weight: bolder;
            color:black;      
        }
        #user{
            font-family: 'Dosis', sans-serif;
            font-weight: bolder;
            color:black; 
            display:flex;
            justify-content: center;
            font-size: 25px;

        }
        #links2{

        padding: 3px;
        font-family:monospace;
        color:rgb(255, 255, 25);
        font-weight: bolder;
        text-decoration: none;
        display:flex;
        border: 2px dotted cyan;  
        justify-content: center;
        font-size: 1rem;
        border-radius: 3px;
        height: 2rem;
        padding-top: 1rem;
        width: 300px;
        margin-left: 3rem;
        }


        


    /* .row::after{
    content: "";
    display: table;
    clear: both;


    } */
    </style>
</head>

<body>
    <header class="header">
        <div class="lefttop">
            <img src="https://blog.trello.com/hubfs/Productivity__236_-_More_Productive_and_Efficient_Events_402x.png"
            alt="events">


        </div>
    </header>
    <button class="btn2" id="text3">
    <a href="{% url 'NeverMissIt:logoutpage' %}" id="log">Logout</a></button>

    <br><br>
    
    <h1 id="head">Profile page</h1>
    <div id="user">Hello, {{ request.user }}</div>
    <br><br>

    <br><br>
    <div class="row">
        <div class="column left">
            <h3 id="grid1">Registered events that are not over yet :</h3>
            <br>
            {% if registered_not_over %}
            <ul  id="grid2">
                {% for e in registered_not_over %}
                <li><a href="{% url 'NeverMissIt:detaileventpage' %}?eventid={{ e.pk }}" id="links2">{{ e.title }}</a></li>
                <br>
                {% endfor %}
            </ul>
            {% else %}
            <h3 id="grid2">No events are yet available</h3>
            {% endif %}
            <br><br>
            <div class="line"><hr>
            </div>
            <h3 id="grid1">Registered events that are over :</h3>
            <br>
            {% if registered_over %}
            <ul id="grid2">
                {% for e in registered_over %}
                <li><a href="{% url 'NeverMissIt:detaileventpage' %}?eventid={{ e.pk }}" id="links2">{{ e.title }}</a></li>
                <br>
                {% endfor %}
            </ul>
            {% else %}
            <h3 id="grid2">No events are yet available</h3>
            {% endif %}
            <br><br>
        </div>
        <div class="column middle">
            <h3 id="grid1">Events available to register :</h3>
            {% if available_events %}
            <ul id="grid3">
                {% for e in available_events %}
                <li><a href="{% url 'NeverMissIt:registereventpage' %}?eventid={{ e.pk }}"id="event">{{ e.title }}</a></li>
                <br>
                {% endfor %}
            </ul>
            {% else %}
            <h3 id="grid2">No events are yet available</h3>
            {% endif %}
            <br><br>
            


        </div>
        
        <div class="column right">
            <button class="btn" id="text3">
            <a href ="{% url 'NeverMissIt:createeventpage' %}" id="link">CREATE AN EVENT</a></button>

            <h3 id="grid1">Created events that are not over yet :</h3>
            <br>
            {% if created_not_over %}
            <ul id="grid2">
                {% for e in created_not_over %}
                <li><a href="{% url 'NeverMissIt:editeventpage' %}?eventid={{ e.pk }}" id="links2">{{ e.title }}</a></li>
                <br>
                {% endfor %}
            </ul>
            {% else %}
            <h3 id="grid2">No events are yet available</h3>
            {% endif %}
            <br><br>
            <div class="line"><hr>
            </div>

            <h3 id="grid1">Created events that are over :</h3>
            <br>
            {% if created_over %}
            <ul id="grid2">
                {% for e in created_over %}
                <li><a href="{% url 'NeverMissIt:detaileventpage' %}?eventid={{ e.pk }}" id="links2">{{ e.title }}</a></li>
                <br>
                {% endfor %}
            </ul>
            {% else %}
            <h3 id="grid2">No events are yet available</h3>
            {% endif %}
            <br><br>
        </div>
    </div>

</body>

</html>

NeverMissIt/templates/NeverMissIt/signuppage.html
<!DOCTYPE html>
<html lang="en">
<head>

    <style>
        body {
            color: orange;
          margin: 0;
          padding: 0;
          background-image: url("https://images.unsplash.com/photo-1505909182942-e2f09aee3e89?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80");
          -webkit-background-size: cover;
          background-size: cover;
          font-family: sans-serif;
        }
        .login_box {
          width: 400px;
          background: rgba(255, 255, 255, 0.863);
          color: #000;
          top: 56%;
          left: 50%;
          position: absolute;
          transform: translate(-50%, -50%);
          box-sizing: border-box;
          padding: 0px 30px;
        }
        .avatar {
          width: 80px;
          height: 80px;
          border-radius: 50%;
          position: absolute;
          top: -30px;
          right: calc(50% - 40px);
        }
        h1 {
          margin-bottom: 10px;
          padding: 0 0;
          text-align: center;
          font-size: 22px;
        }
        .login_box p {
          margin: 0;
          padding: 0;
          font-weight: bold;
        }
        .login_box input {
          width: 100%;
          margin-bottom: 20px;
        }
        .login_box input[type="text"],
        input[type="password"],
        input[type="email"] {
          border: none;
          border-bottom: 1px solid #000;
          background: transparent;
          outline: none;
          height: 40px;
          color: #000;
          font-size: 16px;
        }
        .login_box input[type="submit"] {
          border: none;
          outline: none;
          height: 40px;
          background: #d22938;
          color: #fff;
          font-size: 18px;
          font-weight: bold;
          border-radius: 20px;
        }
        .login_box input[type="submit"]:hover {
          cursor: pointer;
          background: #ffc107;
          color: #000;
        }
        h4 {
    color: black;
    font-weight: bolder;
        }
        .right{
            position: absolute;
            right: 34px;
            top: 20px;
            display: inline-block;
            border-color: black;
        }
        .btn{
            margin: 0px 9px;
            background-color: rgb(255, 232, 21);
            color: yellow;
            padding: 4px 14px;
            border: 2px solid black;
            border-radius: 10px;
            cursor: pointer;
        }
        .btn:hover{
            background-color: grey;
        }
        #text2 a{
            text-decoration: none;
            font-family:cursive;
            font-weight: bolder;
            font-size: unset;
            float: right;
            background-color:transparent;
            color: rgb(0, 0, 0);
        }
  
        </style>
    <title>Signup</title>
</head>
<body>
    <div class="login_box">
        <img src="https://blog.trello.com/hubfs/Productivity__236_-_More_Productive_and_Efficient_Events_402x.png" alt="login_avatar" class="avatar">
        <br><br><br><br>
        <h1>Sign Up</h1>

    <form action="" method="POST">

        {% csrf_token %}

        {{ form.username.label }}
        {{ form.username}}
        {{ form.email.label }}
        {{ form.email}}
        {{ form.password1.label }}
        {{ form.password1}}
        {{ form.password2.label }}
        {{ form.password2}}

        <input type="submit" value='Create User'>
 </form>
    <h4>
    {{form.errors}}
    Already a Customer?  <a href="{% url 'NeverMissIt:loginpage' %}">login</a></h4>
    </div>
     <!-- right box for buttons -->
     <div class="right">
      <button class="btn" id="text2"><a href="{% url 'NeverMissIt:homepage' %}" id="log">Home</a></button>
  </div>
  
</body>
</html>